force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <label>Document Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentController.cls
public with sharing class DocumentController {
    
    @AuraEnabled(cacheable=true)
    public static List<Document__c> getDocuments() {
        return [SELECT Id, Name, Document_Version__c, Document_Category__c FROM Document__c];
    }
    
    @AuraEnabled
    public static void updateDocument(String documentId, String name) {
        Document__c doc = new Document__c(Id = documentId, Name = name);
        update doc;
    }
    
    @AuraEnabled
    public static void deleteDocument(String documentId) {
        delete new Document__c(Id = documentId);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Document__c> searchDocuments(String searchTerm) {
        String searchQuery = '%' + searchTerm + '%';
        return [SELECT Id, Name, Document_Version__c, Document_Category__c 
                FROM Document__c 
                WHERE Name LIKE :searchQuery
                ORDER BY Name];
    }
}